language: node_js
node_js:
  - 0.10


services:
  - mongodb
   
script: "npm test"

before_install:
  - wget http://siliconforks.com/jscoverage/download/jscoverage-0.5.1.tar.bz2
  - tar xvfj jscoverage-0.5.1.tar.bz2
  - cd jscoverage-0.5.1
  - ./configure >/dev/null
  - make >/dev/null
  - cd ..

after_script:
  - rm -f jscoverage-0.5.1.tar.bz2
  - rm -rf jscoverage-0.5.1